package com.compsci.webapp.entity;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Objects;

import lombok.Data;

@Data
public class DailyQuizID implements Serializable{
    private Long id;
    private LocalDate quizDate;

    public DailyQuizID() {}

    public DailyQuizID(Long id, LocalDate quizDate) {
        this.id = id;
        this.quizDate = quizDate;
    }

    // //getters and setters
    // public Long getId() {
    //     return id;
    // }

    // public void setId(Long id) {
    //     this.id = id;
    // }

    // public LocalDate getQuizDate() {
    //     return quizDate;
    // }

    // public void setQuizDate(LocalDate quizDate) {
    //     this.quizDate = quizDate;
    // }

    // //The following code has been generated by chatgpt
    // @Override
    // public boolean equals(Object o) {
    //     if (this == o) return true;
    //     if (o == null || getClass() != o.getClass()) return false;
    //     DailyQuizID that = (DailyQuizID) o;
    //     return Objects.equals(id, that.id) && Objects.equals(quizDate, that.quizDate);
    // }

    // @Override
    // public int hashCode() {
    //     return Objects.hash(id, quizDate);
    // }

}
