name: CICD

on:
    push:
        branches: [deploy-to-ec2]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: Build Project
              run:  |
                cd Backend
                mvn clean install -DskipTests
            - name: Login to docker hub
              run: |
                docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: |
                cd Backend 
                docker build -t naveenjaisankar1999/group12 .
            - name: Publish image to docker hub
              run: |
                docker push naveenjaisankar1999/group12:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Install Docker
              run: |
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
            - name: Pull image from docker hub
              run: |
                docker pull naveenjaisankar1999/group12:latest
            - name: Delete old container
              run: |
                docker rm -f group12-container || true
            - name: Run docker container
              run: |
                docker run -d -p 8080:8080 --name group12-container naveenjaisankar1999/group12
